In [ ]:
import numpy as np
import pandas as pd

admissions = pd.read_csv('data/graduate-student-data.csv')

# Make dummy variables for rank
data = pd.get_dummies(admissions, columns=['rank'])
data = data.astype(int)
# Standarize features
print(data['gpa'].std())
for field in ['gre', 'gpa']:
    mean, std = data[field].mean(), data[field].std()
    data.loc[:, field] = (data[field] - mean) / std
    
# Split off random 10% of the data for testing
np.random.seed(42)
sample = np.random.choice(data.index, size=int(len(data) * 0.9), replace=False)
data, test_data = data.iloc[sample], data.drop(sample)

# Split into features and targets
features, targets = data.drop('admit', axis=1), data['admit']
features_test, targets_test = test_data.drop('admit', axis=1), test_data['admit']

0.47808489090042217


C:\Users\jehad\AppData\Local\Temp\ipykernel_5308\4084157626.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.79801097  0.62588442  1.83783211  0.45274903 -0.58606328  1.49156134
 -0.23979251 -1.62487559 -0.41292789  0.97215519  1.83783211 -1.27860482
  1.49156134  0.97215519  0.97215519 -0.93233405  1.66469673 -1.97114636
  1.83783211 -0.41292789 -0.75919866  0.62588442  0.10647826  0.7990198
  1.49156134  1.83783211  0.27961365 -0.58606328  1.66469673 -0.58606328
 -0.41292789  1.49156134  0.10647826  1.83783211 -1.97114636 -1.62487559
 -0.06665712 -0.58606328 -0.75919866 -0.58606328 -0.23979251 -0.06665712
  0.10647826 -0.75919866  0.97215519 -1.10546943 -0.06665712 -0.75919866
 -1.27860482 -1.62487559  0.45274903 -1.27860482  1.31842596  0.7990198
  0.62588442  1.31842596 -0.23979251 -1.79801097 -1.62487559  0.10647826
  0.27961365 -0.23979251  0.45274903  0.7990198  -0.06665712  0.10647826
  1.31842596  

In [ ]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-np.array(x, dtype=float)))

# TODO: We haven't provided the sigmoid_prime function like we did in
#       the previous lesson to encourage you to come up with a more
#       efficient solution. If you need a hint, check out the comments
#       on solution page from the previous lecture.
def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))
# Use to same seed to make debugging easier
np.random.seed(42)
n_records, n_features = features.shape
features.shape
last_loss = None

# # Initialize weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

# # Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

for e in range(epochs):
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Loop through all records, x is the input, y is `the target
        # Note: We haven't included the h variable from the previous
        #       lesson. You `can add it if you want, or you can calculate
        #       the h together with the output
        # TODO: Calculate the output
        print
        output = sigmoid(np.dot(x, weights))
        
        # TODO: Calculate the error
        error = y - sigmoid(output)
        
        # TODO: Calculate the error term
        error_term = error * output * (1 - output)
        
        # TODO: Calculate the change in weights for this sample
        #       and add it to the total weight change
        del_w +=  error_term * np.array(x, dtype=float)
    # TODO: Update weights using the learning rate and the average change in weights
    weights += learnrate * del_w / n_records
    
    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print(f"Prediction accuracy: {accuracy:.3f}")

Train loss:  0.2627103603926157
Train loss:  0.2180433437951693
Train loss:  0.20369966730519742
Train loss:  0.20297632191001916
Train loss:  0.20815479416709948   WARNING - Loss Increasing
Train loss:  0.2146126024449759   WARNING - Loss Increasing
Train loss:  0.22070357675179098   WARNING - Loss Increasing
Train loss:  0.22604518284405783   WARNING - Loss Increasing
Train loss:  0.23064502403141887   WARNING - Loss Increasing
Train loss:  0.2346053082077629   WARNING - Loss Increasing
Prediction accuracy: 0.725


In [38]:
var = np.random.normal(scale=1 / n_features**.5, size=n_features)
var.shape
print(weights[:,None])

[[ 0.48925657]
 [ 0.22823597]
 [-0.41682944]
 [-2.34465891]
 [-2.73840244]
 [-2.39794605]]


In [37]:
del_w = np.zeros(weights.shape)
for x, y in zip(features.values, targets):
    print(x.shape)
    print(weights.shape)
    break

(6,)
(6,)


In [12]:
print(weights)

[ 0.11146588 -0.05268542  0.256171   -0.89704112 -1.44828984 -1.66994248]


In [ ]:
n_records, n_inputs = features.shape

## Number of hidden units
n_hidden = 2
weights_input_to_hidden = np.random.normal(0, n_inputs**-0.5, size=(n_inputs, n_hidden))

print(weights_input_to_hidden)


[[-0.02939801  0.40969059]
 [ 0.14763729 -0.26336904]
 [ 0.14753914  0.6279008 ]
 [-0.01462592  0.6387631 ]
 [-1.06950646  0.33554029]
 [ 0.03553682 -0.12206924]]
